#!/usr/bin/python3
import py_compile
import os
input_file = os.getenv('PYFILE')
output_file = input_file + 'c'
with open(input_file, 'r') as f:
    source = f.read()
py_compile.compile(source, output_file)
